### ISSUE TITLE
Installation of the add-on  

### ISSUE THREAD

**Issue by mabuh004** [ln-12/blainder-range-scanner#1]
I tried to install the add-on using the provided way, which is: 
(Copy the range_scanner folder to C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons_contrib (Windows).)

However, when I try to activate the add on in Blender, this message appears,  
![error](https://user-images.githubusercontent.com/75952905/132479119-e9cb1fdd-8360-4e65-9b1e-f1eb4ea0503c.png)

How it can be solved? 

Regards.

**Comment by Reitmania** [comment]
Hi, looks like you don't have the pypng python package installed on your computer. Try `pip install pypng`. 

Best regards, reiti

**Comment by ln-12** [comment]
The installation under Windows can be tricky. In case it does not work after the pip command @Reitmania mentioned, try to force the installation of all dependencies for Blenders included python with **admin privileges** (important): 
```
"C:\Program Files\Blender Foundation\Blender 2.83\2.83\python\bin\python.exe" -m pip install laspy h5py pascal_voc_writer pypng pyyaml
```

**Comment by mabuh004** [comment]
how can I try these things? in python? or in blender?

**Comment by Reitmania** [comment]
neither python nor blender, you should open a Windows command window and use the mentioned commands - at best the one of @ln-12 above

(e.g. if you install pypng with pip, you can check the installation in python via "import png". The bug should also disappear in the BlAInder add-on)

**Comment by mabuh004** [comment]
I opened the command window and used the mentioned command, 
![image](https://user-images.githubusercontent.com/75952905/132487051-143379e1-bd25-4898-9365-b6d5101b8608.png)

After that I checked the python using import png, but the bug is still existed in the add-on.

**Comment by ln-12** [comment]
Did you run it as admin?

**Comment by mabuh004** [comment]
@ln-12 when I run it as admin, this happens
![image](https://user-images.githubusercontent.com/75952905/132492007-fe1f2cce-3012-4379-aa2c-60378244cc50.png)

**Comment by ln-12** [comment]
Well, I tried the install procedure on a fresh install of Windows and your error only occurred when running the command prompt as normal user. After starting it as administrator ([for description see here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/jj717276(v=ws.11))), it worked as intended. Your error message also suggests that you do not run it as admin.

**Comment by mabuh004** [comment]
@ln-12 @Reitmania Thank you so much! 
It is working now.
