### ISSUE TITLE
ToF Sensor simulation distortion, when adding Gaussian noise

### ISSUE THREAD

**Issue by kenomo** [ln-12/blainder-range-scanner#11]
When I add Gaussian noise to the simulation of a ToF sensor (scanner type = static), there is noise, but it also seems that everything is projected onto a sphere centered at the camera's origin. Where does this distortion come from?

Thanks.

<img src="https://user-images.githubusercontent.com/30553042/151449217-01e29181-74f8-4279-af8b-280c18fc63f5.png" width="500">

**Comment by ln-12** [comment]
Hey, thanks a lot for reporting! Could you please check if commit e87a14c fixes your problem?
