### ISSUE TITLE
Unable to comprehend examples

### ISSUE THREAD

**Issue by aadi-mishra** [ln-12/blainder-range-scanner#14]
I am trying to replicate classification examples from documentation with a fresh start. I import the chair model provided by you in the .obj format. 
However, I see that the chair model is imported as a whole and not separately as mentioned in the example i.e. Legs and plate. 
I would highly appreciate it if someone can nudge me in the right direction.
Thanks!

**Comment by ln-12** [comment]
Hey @aadi-mishra, the chair model was only included as single mesh. I updated the .obj file to reflect the groups and added the correct materials. Please check again with the latest commit.
