### ISSUE TITLE
RenderSettings.resolution_percentage expected an int type

### ISSUE THREAD

**Issue by ryanjhoffman** [ln-12/blainder-range-scanner#15]
Great work with the plugin! 

I was able to get things working in Blender 3.x with one small change to the code. It seems that "RenderSettings.resolution_percentage" used to allow a float, but now requires an int. My work around was to simply change lidar.py line 319 to the following:

```python
scene.render.resolution_percentage = int(percentage)
```

Perhaps the UI could also be updated to reflect the type change.

I haven't run into any other issues besides this one so far. I would be willing to put together a pull request if that would be useful.

**Comment by ln-12** [comment]
Hey @ryanjhoffman, thanks for reporting! I want to test compatibility with Blender 3.x, but don't have the time right now. I'll come back to this issue later :)

**Comment by ln-12** [comment]
Merged in https://github.com/ln-12/blainder-range-scanner/pull/16. The fix will be available on the main branch when Blender 3.3 LTS is available.
