### ISSUE TITLE
ViewLayer does not contain object

### ISSUE THREAD

**Issue by thomasTUK** [ln-12/blainder-range-scanner#21]
Hello there,

I wanted to prepare different layers for sensor simulation, so I placed Collection.001 on one layer and Collection.002 in a different layer, see attached picture (still active in the View Layer)
![grafik](https://user-images.githubusercontent.com/79101120/187387223-5d2dfb21-eb86-4a52-922a-395b6a3f18eb.png)

No then I am executring the generation of point cloud for one scene, it does not work and I get the error that the other cube is not in the scene

![grafik](https://user-images.githubusercontent.com/79101120/187387637-585ffa94-48d8-4cc3-be83-7f1121278bfb.png)

Collection.001 and Collection.002 contain excactly the same. 
Is this a bug or meant to be? If meant to be, that's alright, just wanted to check in.

**Comment by thomasTUK** [comment]
Here is the file 
[test.zip](https://github.com/ln-12/blainder-range-scanner/files/9451119/test.zip)

**Comment by ln-12** [comment]
Hey @thomasTUK, I remember having issues with collections when implementing the add-on. I currently don't have time to look into it, but I will update you as soon as I know more.

**Comment by thomasTUK** [comment]
Hi @ln-12  no worries, I did just split my Blender File into five each. So For now, I can do my simualtions :)

**Comment by ln-12** [comment]
@thomasTUK commit https://github.com/ln-12/blainder-range-scanner/commit/840d48038697aee966eb48d0676679ff7d08abe7 fixes the issue for me. Could you please check it for your workflow?

**Comment by thomasTUK** [comment]
Did work!
