### ISSUE TITLE
Export point clouds in more commonly used file formats

### ISSUE THREAD

**Issue by YBachmann** [ln-12/blainder-range-scanner#27]
Currently it is only possible to export points clouds in the following formats:

- .las
- .hdf
- .csv

It would be really convinient, if it was possible to export in other formats (.obj, .ply, ...). 
The generated blender objects for visualization can't currently be exported using the built in blender export functions. 

Either add more export options in the "scanner window" of the add-on or enable beeing able to export the visualizations via existing blender export functionality.

**Comment by ln-12** [comment]
Hey @YBachmann, thanks for your suggestion. Unfortunately, I do not have the time at the moment to add any features to the project. However, you can try to implement it yourself and sumbit a PR which I could have a look at. Implementing and .obj should be straight forward when you take the [.csv exporter](https://github.com/ln-12/blainder-range-scanner/blob/main/range_scanner/export/export_csv.py) as a reference.

**Comment by YBachmann** [comment]
Would you be okay with adding an additional pip package (like open3d) to the requirements for writing .ply files?

**Comment by ln-12** [comment]
I don't see any issue as long as the license of that package ist not violated (which I think should be fine here).

**Comment by YBachmann** [comment]
I created a pull request: https://github.com/ln-12/blainder-range-scanner/pull/29 
It is for the Blender3 branch because I use Blender3.

**Comment by ln-12** [comment]
I just merged the Blender3 brnach into main. Thanks again for your contribution and feel free to contact me again when something is not working in the new version.
