### ISSUE TITLE
Trouble reproducing examples: RGB Values in tof (Kinect v2) scan

### ISSUE THREAD

**Issue by fkaufm** [ln-12/blainder-range-scanner#3]
Hi, 
I try to reproduce the examples from the repo. Especially, I am interested in RGB values in the point clouds from materials / textures in Blender. I tried the following, based on example_scenes/part_segmentation_and_image_rendering.blend: 
- Change material of one chair to image texture, see
![blender_chair_image_texture](https://user-images.githubusercontent.com/56821578/140934436-48e18ba3-fe6c-4756-bf5f-94d418851954.png)
- perform scan with tof Kinect v2 scanner
- expected result: RGB values from image texture in pointcloud
- actual result:
![las_pointcloud_kinectv2](https://user-images.githubusercontent.com/56821578/140937256-c17164d4-2d16-400a-92d7-0dac9990bdf0.png)
- Even if I use a RGB color for the material, I get the RGB values as in the example. 
From a glimpse into the source code and the examples I figured, that the RGB scanning is acutally possible. Can you provide the correct material / texture configuration and properties to receive correct results? 
The .blend file and the used texture image can be downloaded from: [https://seafile.rlp.net/d/f2a5db7f0fa043daafc0/](https://seafile.rlp.net/d/f2a5db7f0fa043daafc0/) for reference. 
Some hints on this would be highly appreciated. 
Fabian

**Comment by ln-12** [comment]
@fkaufm thanks again, that's a valid problem. I'll report back if I found a solution!

**Comment by ln-12** [comment]
When refactoring some code in the past, I was missing this part. So thanks a lot for raising this issue! I added a quick workaround in the code and added an example [.blend file](https://github.com/ln-12/blainder-range-scanner/blob/main/example_scenes/texture_usage.blend). 

Unfortunately, texture usage is pretty slow now, but please check if it works for you at all.

**Comment by fkaufm** [comment]
Hi @ln-12 thanks for the quick response and fix. I tested this now, and it works. As you mentioned, it is pretty slow now. Do you think there is a chance to increase the speed of scanning? I plan to use blainder for a more productive ML pipeline, so some more efficiency would be helpful. 
Another question: I cloned the repo today, but after installing I only get scanner category, but no explicit scanners. Are they not implemented yet after the fix?

**Comment by ln-12** [comment]
I think that the slowdown is caused by the workaround to get the right material [here](https://github.com/ln-12/blainder-range-scanner/blob/main/range_scanner/material_helper.py#L40-L75). A solution might be to extract this part and do it somewhere around [here](https://github.com/ln-12/blainder-range-scanner/blob/490df15bcd2a79b0ef301f52f91c7b924fd40423/range_scanner/scanners/generic.py#L233), but right now I don't have time to test it out. Of course you can always try it yourself and propose a PR :)

Scanners shouldn't be affected by the change at all. But again, I have to see if I find time to look into it.

**Comment by ln-12** [comment]
My suggestions has solved the problem for me. The calculation is ~20 times faster in my specific test case. Could you give it a try? I pushed it to the [texture_fix branch](https://github.com/ln-12/blainder-range-scanner/commits/texture_fix).

**Comment by fkaufm** [comment]
@ln-12 Thanks for that fix, massively increased performance. I tested it with some other data and it seems to be working fine. Could / should be merged with main?

**Comment by ln-12** [comment]
I merged it now, thanks again for reporting!
