### ISSUE TITLE
Customize LiDAR's beam distribution angle

### ISSUE THREAD

**Issue by ShunlaiC** [ln-12/blainder-range-scanner#32]
Hi, can I customize the angle of the LiDAR beam in the vertical direction? For example, the vertical beam distribution like RS-Ruby Lite. What should I do? Thanks for your help!

**Comment by ln-12** [comment]
@ShunlaiC Sorry for the very late response, I somehow completely forgot to reply. Of course your can change the distribution as you wish. The ray directions are configured [here](https://github.com/ln-12/blainder-range-scanner/blob/main/range_scanner/scanners/lidar.py#L285-L331). You would have to adjust `xRange` and `yRange` for your scanner type or change the loops [here](https://github.com/ln-12/blainder-range-scanner/blob/main/range_scanner/scanners/lidar.py#L356-L362). Does that help?
