### ISSUE TITLE
How to increase contrast for depthmap?

### ISSUE THREAD

**Issue by kikc9130** [ln-12/blainder-range-scanner#37]
To whom this may concern,

I am currently exploring the use of this software to simulate a drone's depth image scan of a road with potholes in blender for a university project.

As such, I have modeled a simple meshgrid with craters in it to represent a road with pothole defects, and positioned the camera directly above it (to represent a top down drone's eye view of the road) like so:
![image](https://github.com/ln-12/blainder-range-scanner/assets/73805649/3479e683-051e-442d-9a39-520de26179ac)

I have applied the same material on the meshgrid object as the one applied to the original cube in the example file "script_usage.blend".

Using the function for static scans, I have been able to successfully scan the meshgrid and output the resulting depthmap as an image to a desired file location:
![image](https://github.com/ln-12/blainder-range-scanner/assets/73805649/929d64f7-d11a-4f30-9146-f35333979b76)

However, the problem is that, in keeping with real world dimensions, I have set the depth of the potholes to be quite shallow wrt. the scene dimensions, with depths ranging from 25 to 75mm. 
![image](https://github.com/ln-12/blainder-range-scanner/assets/73805649/a9362fd2-1985-4e40-b5fa-5b10b4cfff44)

Therefore, there is a great lack of contrast in the resulting depth image:
![image](https://github.com/ln-12/blainder-range-scanner/assets/73805649/7adc4673-20fe-4dc9-921a-70030c332fb4)

I have verified that the LIDAR capabilities are working by using it to create depthmaps of other objects (like the default arrangement in "script_usage.blend"). 

Is there any way that I can tweak the source code to increase the contrast/sensitivity of the scan so that the difference in depth, although small, could be more apparent? Such that it looks like the result of a blender Z-pass render? An example blender-rendered depth image showcasing potholes of a similar depth, created using the same scene as shown above in the first screenshot, can be found in the image below:
![image](https://github.com/ln-12/blainder-range-scanner/assets/73805649/ac5d22be-a687-4557-b666-3992c96b427d)

I have tried looking around the source code for a bit but unfortunately it is beyond the scope of my undergraduate knowledge and problem solving ability.

Best regards

**Comment by ln-12** [comment]
Hey, sorry for the late reply. You can play around with the depth values and the mapping here: https://github.com/ln-12/blainder-range-scanner/blob/main/range_scanner/export/export_depthmap.py#L10-L33

You just have to transform the interval to your needs and write the new values into the output file.

**Comment by ln-12** [comment]
Do you have any more questions or can we close this issue?

**Comment by kikc9130** [comment]
Dear ln-12,

Thank you for your answer, I had found another workaround to achieve a consistent depthmap gradient using blender's baseline z-pass render to complete the project. So yes I will close the issue with this comment.

Nonetheless, I appreciate your explanation and will no doubt go first to your amazing range scanner if faced with a similar project in the future. It is truly a marvelous software that you have designed.

Apologies for the late correspondence, I wish you all the best with any projects you may have.

Kind regards
